"""lango's tiny Linear: tickets are Markdown files, the board is generated.

Usage (from the lango folder):
    uv run python tickets/board.py                 # regenerate BOARD.md
    uv run python tickets/board.py new "Title"     # create the next LG-NNN ticket from _template.md

Each ticket is LG-NNN-slug.md with a front-matter block (--- ... ---) holding
id, title, status, priority, milestone, mode, labels, depends. Stdlib only.
"""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

HERE = Path(__file__).parent
PREFIX = "LG"
STATUS_ICON = {
    "in-progress": "🔵",
    "review": "🟣",
    "blocked": "🟥",
    "todo": "⬜",
    "backlog": "🗂️",
    "done": "✅",
}
STATUSES = list(STATUS_ICON)  # display order = urgency order
ACTIVE = ("in-progress", "review", "blocked", "todo")
FRONT = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
SLUG_MAX = 50


def parse(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    match = FRONT.match(text)
    if not match:
        raise SystemExit(f"{path.name}: missing front matter")
    fields = {"file": path.name}
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    if fields.get("status") not in STATUS_ICON:
        raise SystemExit(f"{path.name}: unknown status '{fields.get('status')}'")
    return fields


def load() -> list[dict[str, str]]:
    return sorted((parse(p) for p in HERE.glob(f"{PREFIX}-*.md")), key=lambda t: t["id"])


def row(ticket: dict[str, str]) -> str:
    deps = ticket.get("depends", "").strip("[]")
    after = f" · after {deps}" if deps else ""
    mode = " · ⚡fast" if ticket.get("mode") == "fast" else ""
    return (
        f"- {STATUS_ICON[ticket['status']]} **[{ticket['id']}]({ticket['file']})** "
        f"{ticket['title']} · {ticket['priority']}{mode}{after}"
    )


def render(tickets: list[dict[str, str]]) -> str:
    counts = Counter(t["status"] for t in tickets)
    out = [
        "# lango board\n",
        "Generated by `uv run python tickets/board.py`. Edit the ticket files, not this page.\n",
        "| " + " | ".join(f"{STATUS_ICON[s]} {s}" for s in STATUSES) + " | total |",
        "|" + "---|" * (len(STATUSES) + 1),
        "| " + " | ".join(str(counts.get(s, 0)) for s in STATUSES) + f" | {len(tickets)} |\n",
        "## Up next\n",
    ]
    order = {s: i for i, s in enumerate(STATUSES)}
    active = sorted(
        (t for t in tickets if t["status"] in ACTIVE),
        key=lambda t: (order[t["status"]], t["priority"], t["id"]),
    )
    out.extend(row(t) for t in active[:8])
    out.append("\n## By milestone\n")

    milestones: dict[str, list[dict[str, str]]] = {}
    for ticket in tickets:
        milestones.setdefault(ticket["milestone"], []).append(ticket)
    for name, items in sorted(milestones.items()):
        done = sum(t["status"] == "done" for t in items)
        out.append(f"### {name} ({done}/{len(items)} done)\n")
        out.extend(row(t) for t in items)
        out.append("")
    return "\n".join(out)


def new_ticket(title: str) -> Path:
    numbers = [int(t["id"].split("-")[1]) for t in load()]
    ticket_id = f"{PREFIX}-{max(numbers, default=0) + 1:03d}"
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:SLUG_MAX].rstrip("-")
    template = (HERE / "_template.md").read_text(encoding="utf-8")
    body = template.replace("LG-000", ticket_id).replace("Short imperative title", title)
    path = HERE / f"{ticket_id}-{slug}.md"
    path.write_text(body, encoding="utf-8", newline="\n")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command")
    sub.add_parser("new", help="create a ticket").add_argument("title")
    args = parser.parse_args()

    if args.command == "new":
        print(f"created {new_ticket(args.title).name}")
    tickets = load()
    (HERE / "BOARD.md").write_text(render(tickets), encoding="utf-8", newline="\n")
    print(f"BOARD.md: {len(tickets)} tickets, {dict(Counter(t['status'] for t in tickets))}")


if __name__ == "__main__":
    main()
